### ISSUE TITLE
Add a direct application link button

### ISSUE THREAD

**Issue by KrishMunot** [Hackalist/Hackalist.github.io#224]

**Comment by KevinPayravi** [comment]
Hey @KrishMunot! Could you clarify what a direct application link button is?

**Comment by KrishMunot** [comment]
Just a url that redirects to the application link on the hackathon site.

**Comment by paked** [comment]
This is a good idea.

**Comment by KevinPayravi** [comment]
I like the idea, but some issues to consider:
* Maintenance: We often list hackathons before their registration periods open. To be useful, we'll have to check and update whenever a hackathon's registration opens, as well as when it closes. That's something I think will be a struggle to maintain. This could be dealt with if we had registration open/closing dates, but many times these are unannounced or not set in stone.
* Potential for misleading: If we have direct application links, it kind of implies that any listings that don't have application links aren't yet accepting applications - which may not be true, depending on how well our listings are maintained.
* As a hackathon organizer, I'd rather have potential hackathon attendees visit the site first before applying so that appliers know important details about the event before applying (venue details, FAQ, restrictions, etc.). Likewise, I think having application links allows people to quickly go down and shotgun-apply to many hackathons they won't attend - something else organizers may not want.

**Comment by KevinPayravi** [comment]
(accidentally closed, re-opening)

**Comment by adeora7** [comment]
@KevinPayravi  Many hackathons have mailing lists. There can we a button or one/two column form to apply for the same in the description. This might deal with the problems mentioned above.

**Comment by KevinPayravi** [comment]
@adeora7 Not a bad idea! Quick access to mailing lists would be nice.

From the top of my head though, I don't recall seeing _too_ many hackathons with mailing lists. We should do a rough study of what % of hackathons have mailing lists to see if it's worth adding a field.

**Comment by KevinPayravi** [comment]
Closing as stale; can be re-opened if someone desires to continue discussion.
